# Default config: Should become production mode
default:
  reg_name: "default"
  reg_dir: !expr here::here("registries", reg_name)
  result_path: !expr here::here("results", reg_name)
  seed: 2024
  task_dim_max: !expr 1e6
  learner_threads: 1 # Careful to adjust based on available hardware
  resampling:
    inner:
      strategy: "repeated_cv"
      folds: 3
      repeats: 2
    outer:
      strategy: "OML" # "OML" uses existing resamplings, otherwise creat enew mlr3 resampling
      folds: 3
      repeats: 2
  tuning:
    # budget = evals + n_params * multiplier
    evals: 200
    multiplier: 0
    runtime: !expr  6 * 24 * 60 * 60 # expected in seconds
    tuner: "mbo"
  fallback:
    inner: true
    outer: true
  timeout:
    # provided in hours here
    base:
      train: 12
      predict: 4
    autotuner:
      train: 156
      predict: 12

production:
  reg_name: "production"

production-parallel:
  reg_name: "production-parallel"
  learner_threads: 10

trial:
  reg_name: "trial"
  tuning:
    # budget = evals + n_params * multiplier
    evals: 10
    multiplier: 0
    runtime: !expr 24 * 60 * 60 # expected in seconds
    tuner: "mbo"
  fallback:
    inner: true
    outer: false

debug:
  reg_name: "debug"
  resampling:
    inner:
      strategy: "holdout"
    outer:
      strategy: "OML"
  tuning:
    evals: 1
    multiplier: 0
    runtime: !expr 24 * 60 * 60 # expected in seconds
    tuner: "random_search"
  fallback:
    inner: false
    outer: false
