# Default config: Should become production mode
default:
  reg_name: "default"
  reg_dir: !expr here::here("registries", reg_name)
  result_path: !expr here::here("results", reg_name)
  seed: 2024
  # Initial limit on tasks to get from OpenML suite, dim = n * p
  task_dim_max: !expr 1e6
  learner_threads: 1 # Careful to adjust based on available hardware
  resampling:
    inner:
      strategy: "repeated_cv"
      folds: 3
      repeats: 2
    outer:
      strategy: "OML" # "OML" uses existing resamplings, otherwise creat enew mlr3 resampling
      folds: 3
      repeats: 2
  tuning:
    # budget = evals + n_params * multiplier
    evals: 200
    multiplier: 0
    runtime: !expr  6 * 24 * 60 * 60 # expected in seconds
    tuner: "mbo"
  fallback:
    inner: true
    outer: true
  timeout:
    # provided in hours here
    base:
      train: 12
      predict: 4
    autotuner:
      train: 138
      predict: 6

production:
  reg_name: "production"

production_v1:
  reg_name: "production_v1"

trial:
  reg_name: "trial"
  tuning:
    evals: 10
    multiplier: 0
    runtime: !expr 24 * 60 * 60
    tuner: "mbo"
  fallback:
    inner: true
    outer: false
